// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiXm3hPBdqkKA8mRBegUhz3bCBIeT2MWc',
    appId: '1:772116009786:web:37cb96bac0dac0ee2ff603',
    messagingSenderId: '772116009786',
    projectId: 'sistem-tracker-t',
    authDomain: 'sistem-tracker-t.firebaseapp.com',
    storageBucket: 'sistem-tracker-t.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-BvZ8vbRvQZebPiyUnPGeLHWcf8bzbSE',
    appId: '1:772116009786:android:923768118381c89b2ff603',
    messagingSenderId: '772116009786',
    projectId: 'sistem-tracker-t',
    storageBucket: 'sistem-tracker-t.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-kmQAvL_MW_3hkKISiaq-wAZqqdLBO48',
    appId: '1:772116009786:ios:c93c7cf887d7cbe82ff603',
    messagingSenderId: '772116009786',
    projectId: 'sistem-tracker-t',
    storageBucket: 'sistem-tracker-t.firebasestorage.app',
    iosBundleId: 'com.tracker.sistem.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-kmQAvL_MW_3hkKISiaq-wAZqqdLBO48',
    appId: '1:772116009786:ios:c93c7cf887d7cbe82ff603',
    messagingSenderId: '772116009786',
    projectId: 'sistem-tracker-t',
    storageBucket: 'sistem-tracker-t.firebasestorage.app',
    iosBundleId: 'com.tracker.sistem.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiXm3hPBdqkKA8mRBegUhz3bCBIeT2MWc',
    appId: '1:772116009786:web:8a180b0a08e65bc32ff603',
    messagingSenderId: '772116009786',
    projectId: 'sistem-tracker-t',
    authDomain: 'sistem-tracker-t.firebaseapp.com',
    storageBucket: 'sistem-tracker-t.firebasestorage.app',
  );
}
