import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'providers/dashboard_provider.dart';
import 'services/firestore_ai_service.dart';
import 'ui/layout/main_layout.dart';
import 'ui/theme/app_theme.dart';
import 'firebase_options.dart'; // Will be generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
     await Firebase.initializeApp(
       options: DefaultFirebaseOptions.currentPlatform,
     );
  } catch (e) {
      // Allow running without config for UI testing (though Firebase features will fail)
      print("Firebase Init Failed (Run 'flutterfire configure' to fix): $e");
  }
  runApp(const TransportMonitoringApp());
}

class TransportMonitoringApp extends StatelessWidget {
  const TransportMonitoringApp({super.key});

  @override
  Widget build(BuildContext context) {
    // 1. Initialize Services (Dependency Injection)
    // Using Real Firestore Service for Production
    final aiService = FirestoreAiService();

    return MultiProvider(
      providers: [
        ChangeNotifierProvider(
          create: (_) => DashboardProvider(aiService),
        ),
      ],
      child: MaterialApp(
        title: 'MonitorPro - Transporte y Retail',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.lightTheme,
        home: const MainLayout(),
      ),
    );
  }
}
